version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nfl
      POSTGRES_PASSWORD: nflpw
      POSTGRES_DB: nfl_db
    ports:
      - "5432:5432"
    volumes:
      - nfl_pgdata:/var/lib/postgresql/data
  
  airflow:
    image: apache/airflow:2.9.0
    environment:
      -AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  nfl_pgdata: